# Generated by Django 3.2.8 on 2021-10-31 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Nazwa influencera')),
                ('title', models.CharField(max_length=50, verbose_name='Nazwa filmu')),
                ('category', models.CharField(max_length=50, verbose_name='Kategoria filmu')),
                ('content', models.TextField(max_length=500, verbose_name='HTML EMBEDED do filmu')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
    ]
