# Generated by Django 3.2.8 on 2022-01-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Nazwa filmu'),
        ),
    ]
