# Generated by Django 3.2.8 on 2021-10-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='content',
            field=models.TextField(max_length=800, verbose_name='HTML EMBEDED do filmu'),
        ),
    ]
