# Generated by Django 3.2.8 on 2021-10-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20211031_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='insta_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='movie',
            name='tiktok_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='movie',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
