# Generated by Django 3.2.8 on 2022-01-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('TRAVEL', 'TRAVEL'), ('SZTUKA', 'SZTUKA'), ('BEAUTY', 'BEAUTY'), ('ŚMIESZNE', 'ŚMIESZNE'), ('GAMING', 'GAMING'), ('LIFESTYLE', 'LIFESTYLE'), ('SPORT', 'SPORT')], default='unassigned', max_length=50, verbose_name='Kategoria filmu'),
        ),
    ]
