# Generated by Django 3.2.8 on 2021-10-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20211031_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='content',
            field=models.TextField(max_length=1200, verbose_name='HTML EMBEDED do filmu'),
        ),
    ]
