# Generated by Django 3.2.8 on 2021-10-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_movie_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='content',
            field=models.TextField(max_length=5000, verbose_name='HTML EMBEDED do filmu'),
        ),
    ]
