# Generated by Django 3.2.8 on 2021-11-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_movie_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(blank=True, choices=[('HOT-TOP', 'HOT-TOP'), ('ODKRYCIA', 'ODKRYCIA'), ('BEAUTY', 'BEAUTY'), ('ŚMIESZNE', 'ŚMIESZNE'), ('GAMING', 'GAMING'), ('LIFESTYLE', 'LIFESTYLE'), ('SZTUKA', 'SZTUKA'), ('SPORT', 'SPORT')], max_length=50, null=True, verbose_name='Kategoria filmu'),
        ),
    ]
