# Generated by Django 3.2.8 on 2021-11-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='source',
            field=models.CharField(choices=[('YouTube', 'YouTube'), ('TikTok', 'TikTok'), ('Instagram', 'Instagram'), ('Other', 'Other')], default='unassigned', max_length=50, verbose_name='Źródło filmu'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('HOT-TOP', 'HOT-TOP'), ('ODKRYCIA', 'ODKRYCIA'), ('BEAUTY', 'BEAUTY'), ('ŚMIESZNE', 'ŚMIESZNE'), ('GAMING', 'GAMING'), ('LIFESTYLE', 'LIFESTYLE'), ('SZTUKA', 'SZTUKA'), ('SPORT', 'SPORT')], default='unassigned', max_length=50, verbose_name='Kategoria filmu'),
        ),
    ]
