# Generated by Django 3.2.8 on 2021-11-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20211121_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='source',
            field=models.CharField(choices=[('YouTube', 'YouTube'), ('TikTok', 'TikTok'), ('Instagram', 'Instagram'), ('Other', 'Other'), ('Promo', 'Promo')], default='unassigned', max_length=50, verbose_name='Źródło filmu'),
        ),
    ]
