# Generated by Django 3.2.8 on 2021-11-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_movie_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
    ]
