# Generated by Django 3.2.8 on 2021-11-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_movie_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='promotion',
            field=models.BooleanField(default=False, verbose_name='PROMOCJA FILMU'),
        ),
    ]
