# Generated by Django 3.2.8 on 2021-12-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_movie_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='source',
            field=models.CharField(choices=[('YouTube', 'YouTube'), ('TikTok', 'TikTok'), ('Instagram', 'Instagram'), ('Other', 'Other')], default='unassigned', max_length=50, verbose_name='Źródło filmu'),
        ),
    ]
