# Generated by Django 3.2.8 on 2021-12-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_ipmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='fire_likes',
            field=models.ManyToManyField(blank=True, related_name='fire_likes', to='pages.IpModel'),
        ),
    ]
